apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: spring-cloud-contract-broker
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: spring-cloud-contract-broker
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: spring-cloud-contract-broker
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "500m"
                  limits:
                    memory: "1Gi"
                    cpu: "1000m"
  - target:
      kind: ConfigMap
      name: spring-cloud-contract-broker
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: spring-cloud-contract-broker
      data:
        SPRING_PROFILES_ACTIVE: "prod"
  - target:
      kind: HorizontalPodAutoscaler
      name: spring-cloud-contract-broker
    patch: |
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: spring-cloud-contract-broker
      spec:
        maxReplicas: 10

commonLabels:
  app.kubernetes.io/name: spring-cloud-contract-broker
  app.kubernetes.io/part-of: spring-cloud-contract-broker
  app.kubernetes.io/managed-by: kustomize
  environment: prod
