spring:
  application:
    name: verification-processor
  kafka:
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.verification"
