apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-cloud-contract-broker
  labels:
    app.kubernetes.io/name: spring-cloud-contract-broker
    app.kubernetes.io/part-of: spring-cloud-contract-broker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-cloud-contract-broker
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
